services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "abcDEF123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
  
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5000"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=CycleDB;User Id=sa;Password=abcDEF123!;TrustServerCertificate=True;"
    ports:
      - "5000:5000"
    depends_on:
      - mssql


  webui:
    image: webui
    build:
      context: .
      dockerfile: WebUI/Dockerfile
    environment:
      ApiBaseUrl: "http://api:5000/odata/"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "5001:8080"
volumes:
  sqlvolume: {}

